name: '🐛 Bug Report'
description: Report something that is broken or not working as intended.
title: '[Bug]: '
labels: ['type: bug 🐛']
projects: ['khoait/1']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component-id
    attributes:
      label: Component
      description: Which Component/Utility is affected
      options:
        - Lookdown
        - PolyLookup
        - TimePicker
    validations:
      required: true

  - type: input
    id: component-version
    attributes:
      label: Component version
      description: |
        Which version of the component are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: |
        What is the current behavior that you are experiencing?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        What is the behavior that you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Explain how to cause the issue in the provided reproduction.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Eg. screenshots, solution version, Power Platform environment, ...
